import type { Metadata } from "next";
import "./globals.css";
// components
import { Navbar, Footer } from "@/components/organisms";

export const metadata: Metadata = {
  title: "Marcos Elias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Navbar></Navbar>
        <main className="flex-grow">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
